#include <iostream>
#include "TFile.h"
#include "TH2D.h"
#include "TCanvas.h"
#include "TStyle.h"

void extract_images(const char* rootFilePath, const char* imageOutputPath = "charge_map_export.png") {
    // 1. Open the ROOT file generated by save_histogram.C
    TFile *file = TFile::Open(rootFilePath, "READ");
    if (!file || file->IsZombie()) {
        std::cerr << "Error: Could not open file " << rootFilePath << std::endl;
        return;
    }

    // 2. Retrieve the histogram object
    // Note: In save_histogram.C, the TH2D was named "charge_map;1"
    TH2D *hist = (TH2D*)file->Get("charge_map;1");
    
    if (!hist) {
        std::cerr << "Error: Histogram 'charge_map;1' not found in " << rootFilePath << std::endl;
        file->Close();
        return;
    }

    // 3. Set visual styles for a professional detector plot
    gStyle->SetOptStat(0);       // Hide the statistics box
    gStyle->SetPalette(kBird);   // Use a modern color palette

    // 4. Create a Canvas and Draw
    TCanvas *c1 = new TCanvas("c1", "Image Export", 1000, 800);
    c1->SetRightMargin(0.15);    // Make room for the color scale
    
    hist->SetTitle("Pixel Detector Charge Map;Pixel X;Pixel Y;Charge (Amplitude)");
    hist->Draw("COLZ");          // Draw with Color Palette

    // 5. Save the image
    c1->SaveAs(imageOutputPath);
    
    std::cout << "Successfully exported " << imageOutputPath << " from " << rootFilePath << std::endl;

    // 6. Cleanup
    delete c1;
    file->Close();
}